=== fdepablo/WsLMSGIActividades_24_25/Actividad_15/ciudad.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ciudad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-ZÑÁÉÍÓÚ][a-zñáéíóú]{2,19}"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="alcalde">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z]\D{0,9}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="apellidos">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z]\D{0,24}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="telefono">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\+34\d{9}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="correo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="funcionarios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="funcionario" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre"></xs:element>
                                        <xs:element name="fecha_nacimiento">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{2}/\d{2}/\d{4}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="codigo_postal">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{5}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="contraseña">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Z](\d\d)+[%$@!]"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="cuenta_bancaria">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="ES(\d{4}\s){2}\d{4}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="codigo">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\D\D-\d{2,5}"></xs:pattern>
                        <!-- 
                        <xs:pattern value="\D{2}-\d{2,5}"></xs:pattern>
                        -->
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== fdepablo/WsLMSGIActividades_24_25/Actividad_15/ciudad.xml
<?xml version="1.0" encoding="UTF-8"?>
<ciudad codigo="AB-12345" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="ciudad.xsd">
    <nombre>Madrid</nombre>
    <alcalde>
        <nombre>Juan</nombre>
        <apellidos>Perez</apellidos>
        <telefono>+34123456789</telefono>
        <correo>juan.perez@example.com</correo>
    </alcalde>
    <funcionarios>
        <funcionario>
            <nombre>Maria</nombre>
            <fecha_nacimiento>01/01/1980</fecha_nacimiento>
            <codigo_postal>28001</codigo_postal>
            <contrase単a>A12234545$</contrase単a>
            <cuenta_bancaria>ES1234 5678 1234</cuenta_bancaria>
        </funcionario>
        <funcionario>
            <nombre>Carlos</nombre>
            <fecha_nacimiento>15/05/1975</fecha_nacimiento>
            <codigo_postal>28002</codigo_postal>
            <contrase単a>B34@</contrase単a>
            <cuenta_bancaria>ES2345 6789 2345</cuenta_bancaria>
        </funcionario>
    </funcionarios>
</ciudad>
