=== fdepablo/WsLMSGIActividades_24_25/Actividad_11_12/videojuego.dtd
<!ELEMENT videojuego (nombre, fecha_creacion, nota, programadores, compañia, web)>
<!ELEMENT fecha_creacion (#PCDATA)>
<!ELEMENT nota (#PCDATA)>
<!ELEMENT programadores (programador+)>
<!ELEMENT programador (nombre, apellidos, dni, fecha_de_nacimiento, direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT fecha_de_nacimiento (#PCDATA)>
<!ELEMENT direccion (tipo_de_via, nombre_de_la_via, codigo_postal, pais)>
<!ELEMENT tipo_de_via (#PCDATA)>
<!ELEMENT nombre_de_la_via (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT compañia (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ATTLIST programador id ID #REQUIRED>
<!ATTLIST videojuego id ID #REQUIRED>

=== fdepablo/WsLMSGIActividades_24_25/Actividad_11_12/videojuego.xml
<!DOCTYPE videojuego SYSTEM "videojuego.dtd">
<videojuego id="V01">
    <nombre>Final Fantasy VII</nombre>
    <fecha_creacion>12/12/1997</fecha_creacion>
    <nota>10</nota>
    <programadores>
        <programador id="P01">
            <nombre>Agustin</nombre>
            <apellidos>Ortega</apellidos>
            <dni>12345678M</dni>
            <fecha_de_nacimiento>12/12/1997</fecha_de_nacimiento>
            <direccion>
                <tipo_de_via>Calle</tipo_de_via>
                <nombre_de_la_via>Gran Via</nombre_de_la_via>
                <codigo_postal>28224</codigo_postal>
                <pais>España</pais>
            </direccion>
        </programador>
         <programador id="P02">
            <nombre>Maria</nombre>
            <apellidos>Gomez</apellidos>
            <dni>87654321X</dni>
            <fecha_de_nacimiento>23/05/1990</fecha_de_nacimiento>
            <direccion>
                <tipo_de_via>Avenida</tipo_de_via>
                <nombre_de_la_via>Diagonal</nombre_de_la_via>
                <codigo_postal>08018</codigo_postal>
                <pais>España</pais>
            </direccion>
        </programador>
        <programador id="P03">
            <nombre>Carlos</nombre>
            <apellidos>Lopez</apellidos>
            <dni>11223344Z</dni>
            <fecha_de_nacimiento>15/08/1985</fecha_de_nacimiento>
            <direccion>
                <tipo_de_via>Plaza</tipo_de_via>
                <nombre_de_la_via>Mayor</nombre_de_la_via>
                <codigo_postal>28013</codigo_postal>
                <pais>España</pais>
            </direccion>
        </programador>
    </programadores>
    <compañia>Square</compañia>
    <web>
    <![CDATA[ 
        <html>
            <head>
                <title>mi pagina web de ffvII</title>
            </head>
            <body>
                <h1>Final Fantasy :) VII</h1>
            </body>
        </html>
    ]]>
    </web>
</videojuego>
