=== fdepablo/WsLMSGIActividades_24_25/Actividad_13/Actividad13_02_XML_DTD.dtd
<!ELEMENT Empresa (Nombre, NIF, Española, Capital_Social, Direccion_Empresa, Empleados)>

<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT NIF (#PCDATA)>
<!ELEMENT Española (#PCDATA)>
<!ELEMENT Capital_Social (#PCDATA)>

<!ELEMENT Direccion_Empresa (Tipo_de_via, Nombre_de_via, CP, Pais)>
<!ELEMENT Tipo_de_via (#PCDATA)>
<!ELEMENT Nombre_de_via (#PCDATA)>
<!ELEMENT CP (#PCDATA)>
<!ELEMENT Pais (#PCDATA)>

<!ELEMENT Empleados (Empleado+)>
<!ELEMENT Empleado (Nombre, Apellido+, DNI, Extranjero, Fecha_nacimiento, Salario, Direccion+, Esta_casado?)>
<!ELEMENT Apellido (#PCDATA)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT Extranjero (#PCDATA)>
<!ELEMENT Fecha_nacimiento (#PCDATA)>
<!ELEMENT Salario (#PCDATA)>
<!ELEMENT Direccion (Direccion_Empleado, Pais_Empleado)>
<!ELEMENT Direccion_Empleado (#PCDATA)>
<!ELEMENT Pais_Empleado (#PCDATA)>

<!ELEMENT Esta_casado (#PCDATA)>

<!ENTITY España "ESPAÑA">

=== fdepablo/WsLMSGIActividades_24_25/Actividad_13/Actividad13_02_XML_DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Empresa SYSTEM "Actividad13_02_XML_DTD.dtd">
<Empresa>
    <Nombre>Hewlett Packard Enterprise (HPE)</Nombre>
    <NIF>Z1234567M</NIF>    
    <Española>false</Española>
    <Capital_Social>23739340.75</Capital_Social>
    <Direccion_Empresa>
        <Tipo_de_via>Calle</Tipo_de_via>
        <Nombre_de_via>Vicente Aleixandre, 1, Las Rozas</Nombre_de_via>
        <CP>28232</CP>
        <Pais>España</Pais>
    </Direccion_Empresa>
    <Empleados>
        <Empleado>
            <Nombre>Ruben</Nombre>
            <Apellido>Gonzalvez</Apellido>
            <Apellido>Vargas</Apellido>
            <DNI>M4353566F</DNI>
            <Extranjero>true</Extranjero>
            <Fecha_nacimiento>1990-02-03</Fecha_nacimiento>
            <Salario>6500</Salario>
            <Direccion>
                <Direccion_Empleado>Avenida de la Vega 15, 28108, Alcobendas (Madrid)</Direccion_Empleado>
                <Pais_Empleado>Colombia</Pais_Empleado>
            </Direccion>
        </Empleado>        
    </Empleados>
</Empresa>
